### ISSUE TITLE
Test setup/teardown not working

### ISSUE THREAD

**Issue by Leglaine** [Leglaine/express-api-template#1]
In api/controllers/users.test.js there is an afterAll hook that is supposed to delete all documents from the users collection, it is not working. I've tried using async/await as well, but then it times out and the tests won't even pass.

**Comment by nicbaughman** [comment]
Looks like in your `user.model.js` you don't have a `deleteMany()` which is being called in `afterEach`. I am just guessing line 6 in `user.test.js` does nothing because of this.

**Comment by nicbaughman** [comment]
Curious to know what was needed to resolve this issue?
