### ISSUE TITLE
Outlook won't authenticate smtp

### ISSUE THREAD

**Issue by Leglaine** [Leglaine/express-api-template#2]
I was able to send emails from an outlook account using nodemailer for about two days, and now it's not working anymore. It keeps throwing a 535 'Authentication unsuccessful' error, though I haven't changed any of my account settings.

**Comment by nicbaughman** [comment]
Looks like there are some existing conversations about this on nodemailer repo
https://github.com/nodemailer/nodemailer/issues/920

Looks like could be due to symbols in a password maybe. So making a password with simple characters and numbers might fix things.

**Comment by nicbaughman** [comment]
Was the password the main solution for this?

**Comment by Leglaine** [comment]
@nicbaughman 
> Was the password the main solution for this?

Haha well yes, but not because of special characters or anything. I was apparently just using the wrong password. I'm still a bit perplexed because I keep it as an environment variable and I don't remember touching it, but it's working now so I'm happy! Thanks for your help, I feel like an idiot lol.
